title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: HuterCR
  github: HuterCR

plugins:
 - jekyll-feed
 - jekyll-seo-tag

